import { useState } from "react";
import Link from "next/link";
import Layout from "../components/Layout";
import { demoFundingSummary, demoPartners, demoProjects, demoUpdates, ecosystemSpaces } from "../data/bawonDemo";

const copy = {
  "financer-mon-projet": ["Financer mon projet", "Dossier guidé", "Prépare ton dossier, sauvegarde une version de démonstration et découvre le parcours de revue BAWON+."],
  soutenir: ["Soutenir un projet", "Contribution encadrée", "Aucune collecte n'est ouverte : voici le format que prendra une campagne clairement documentée."],
  investir: ["Investir", "Opportunités en préparation", "Aucune opportunité réelle n'est ouverte. Cette interface montre le futur format de documentation et de sélection."],
  "bawon-connect": ["Bawon Connect", "Besoin ↔ solution", "Un espace de mise en relation structuré, sans marketplace entre particuliers."],
  accompagnement: ["Accompagnement Bawon", "De l'idée au dossier solide", "Diagnostic, stratégie, prévisionnel, préparation investisseurs et développement international."],
  partenaires: ["Nos partenaires", "Répertoire qualifié", "Les profils ci-dessous sont des exemples d'interface ; aucun partenariat réel n'est revendiqué."],
  actualites: ["Actualités", "Activité et suivi", "Aperçu de la future activité BAWON+, distinct des actualités vérifiées qui seront publiées ultérieurement."],
  "bawon-produits": ["BAWON Produits", "Marques & créations", "Un espace de présentation pour les produits BAWON : collections, prototypes, fiches et développements à venir."],
  "bawon-boissons": ["BAWON Boissons", "Expériences & distribution", "Un espace dédié aux boissons BAWON, de la création produit à la distribution internationale."],
  "bawon-industrie": ["BAWON Industrie", "Production & transformation", "Un espace pour les capacités de production, la transformation et les futurs partenariats industriels."],
};

function DemoBanner() { return <div className="mb-8 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#d6b26f]/30 bg-[#d6b26f]/10 px-4 py-3 text-xs text-[#f3d99d]"><span className="font-semibold uppercase tracking-[.15em]">Environnement de démonstration</span><span>Exemples fictifs · aucune opération financière n'est ouverte</span></div>; }

function FundingMetrics() { return <div className="mb-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{demoFundingSummary.map(([value, label]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><strong className="block text-xl font-semibold text-white sm:text-2xl">{value}</strong><span className="mt-1 block text-xs leading-5 text-white/55">{label}</span></div>)}</div>; }

function ProjectCards({ interactive = false }) {
  const [selected, setSelected] = useState([]);
  const toggle = (id) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  return <><FundingMetrics /><div className="grid gap-5 lg:grid-cols-3">{demoProjects.map((project) => <article key={project.id} className="bawon-card overflow-hidden p-0"><div className="relative h-48 overflow-hidden border-b border-white/10"><img src={project.image} alt="Visuel de démonstration du projet" className="h-full w-full object-cover transition duration-700 hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#09060e] via-transparent to-transparent" /><span className="absolute bottom-3 left-4 rounded-full border border-[#d6b26f]/40 bg-black/60 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.12em] text-[#f3d99d]">{project.sector}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-semibold">{project.title}</h3><p className="mt-1 text-sm text-white/55">{project.location}</p></div><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] text-white/70">{project.stage}</span></div><div className="mt-5 flex items-end justify-between"><div><span className="text-xs text-white/55">Engagé · démo</span><b className="mt-1 block text-lg">{project.committed}</b></div><div className="text-right"><span className="text-xs text-white/55">Objectif</span><b className="mt-1 block">{project.objective}</b></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#d6b26f] to-violet-400" style={{ width: `${project.progress}%` }} /></div><div className="mt-2 flex justify-between text-xs text-white/60"><span>{project.progress}% couvert</span><span>{project.deadline}</span></div><p className="mt-4 border-y border-white/10 py-3 text-xs leading-5 text-white/65">{project.milestone}</p><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-white/60">Ticket dès <b className="text-white">{project.ticket}</b> · {project.backers} intérêts</span>{interactive && <button type="button" onClick={() => toggle(project.id)} className="shrink-0 rounded-full border border-white/20 px-3 py-1.5 text-xs font-semibold text-white hover:border-[#d6b26f]">{selected.includes(project.id) ? "Dans ma sélection" : "Comparer"}</button>}</div></div></article>)}</div>{interactive && <p className="mt-5 text-sm text-white/60">{selected.length ? `${selected.length} dossier(s) dans ta sélection de démonstration.` : "Choisis jusqu'à trois dossiers pour simuler une sélection."}</p>}</>;
}

function FundingForm() {
  const [saved, setSaved] = useState(false);
  return <><FundingMetrics /><div className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><aside className="bawon-card"><p className="text-sm font-semibold">Parcours du dossier</p><ol className="mt-5 space-y-4 text-sm text-white/65">{["Identité", "Projet", "Équipe & marché", "Budget", "Documents", "Revue BAWON"].map((step, index) => <li key={step} className="flex gap-3"><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs ${index === 0 ? "bg-[#d6b26f] text-black" : "border border-white/20"}`}>{index + 1}</span>{step}</li>)}</ol><div className="mt-7 border-t border-white/10 pt-5"><p className="text-xs uppercase tracking-[.14em] text-[#d6b26f]">Modèle démo</p><p className="mt-2 text-sm leading-6 text-white/65">Financement → jalon → preuve → validation → décaissement. Aucun décaissement n’est réel sur cette version.</p></div></aside><form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="bawon-card"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Nom du projet<input required placeholder="Ex. Cacao Lakay" className="mt-2 w-full rounded-xl border border-white/15 bg-black/30 px-3 py-3 text-white outline-none focus:border-[#d6b26f]" /></label><label className="text-sm">Secteur<select className="mt-2 w-full rounded-xl border border-white/15 bg-black/30 px-3 py-3 text-white outline-none focus:border-[#d6b26f]"><option>Agro-industrie</option><option>Énergie</option><option>Services</option><option>Culture & création</option></select></label></div><label className="mt-4 block text-sm">Objectif du projet<textarea placeholder="Décris le besoin, le marché et l'impact recherché." className="mt-2 min-h-28 w-full rounded-xl border border-white/15 bg-black/30 px-3 py-3 text-white outline-none focus:border-[#d6b26f]" /></label><div className="mt-5 flex flex-wrap items-center gap-4"><button className="bawon-button-primary" type="submit">Sauvegarder le brouillon démo</button>{saved && <span className="text-sm text-emerald-300">Brouillon simulé enregistré sur cet appareil.</span>}</div></form></div></>;
}

function PartnerGrid() { return <div className="grid gap-4 md:grid-cols-3">{demoPartners.map((partner) => <article key={partner.name} className="bawon-card"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-[#d6b26f] to-violet-600 font-black text-black">B+</div><p className="mt-6 text-xs uppercase tracking-[.15em] text-[#d6b26f]">{partner.type}</p><h3 className="mt-2 text-lg font-semibold">{partner.name}</h3><p className="mt-1 text-sm text-white/55">{partner.country}</p><p className="mt-6 border-t border-white/10 pt-4 text-sm text-white/70">Correspondance : {partner.match}</p></article>)}</div>; }

function ConnectBoard() { return <div className="grid gap-4 lg:grid-cols-3">{[["Besoins projet", ["Financement", "Distribution", "Expertise export"]], ["Solutions disponibles", ["Investisseur à qualifier", "Partenaire commercial", "Conseil réglementé"]], ["Suivi BAWON", ["1 dossier en revue", "2 mises en relation", "0 décision finale"]]].map(([title, rows]) => <section key={title} className="bawon-card"><h3 className="font-semibold">{title}</h3><div className="mt-5 space-y-3">{rows.map((row, index) => <div key={row} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><span className="mr-2 text-[#d6b26f]">0{index + 1}</span>{row}</div>)}</div></section>)}</div>; }

function UpdateFeed() { return <div className="space-y-3">{demoUpdates.map(([type, project, message, time]) => <article key={message} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-4"><div><span className="text-xs uppercase tracking-[.14em] text-[#d6b26f]">{type}</span><p className="mt-1 font-semibold">{project}</p><p className="mt-1 text-sm text-white/60">{message}</p></div><span className="text-xs text-white/45">{time}</span></article>)}</div>; }

function EcosystemPole({ slug }) { const space = ecosystemSpaces[slug]; return <><section className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.035] md:grid md:grid-cols-[.95fr_1.05fr]"><img src={space.image} alt={`Visuel de démonstration ${space.label}`} className="h-64 w-full object-cover md:h-full" /><div className="p-7 md:p-10"><p className="bawon-eyebrow">{space.eyebrow}</p><h2 className="mt-4 text-3xl font-semibold leading-tight">{space.headline}</h2><p className="mt-5 leading-7 text-white/70">{space.intro}</p><Link href="/contact" className="mt-7 inline-flex rounded-full border border-[#d6b26f]/50 px-4 py-2 text-sm font-semibold text-[#f3d99d]">Recevoir les prochaines informations</Link></div></section><section className="mt-5 grid grid-cols-3 gap-3">{space.metrics.map(([value, label]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><strong className="block text-xl sm:text-2xl">{value}</strong><span className="mt-1 block text-xs leading-5 text-white/55">{label}</span></div>)}</section><section className="mt-5 grid gap-4 md:grid-cols-3">{space.cards.map(([title, category, description], index) => <article key={title} className="bawon-card"><span className="text-xs text-[#d6b26f]">0{index + 1}</span><p className="mt-6 text-xs uppercase tracking-[.14em] text-white/45">{category}</p><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{description}</p><Link href="/contact" className="mt-6 block text-sm text-[#f3d99d]">Demander les informations →</Link></article>)}</section><section className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-5"><p className="text-sm font-semibold">Feuille de route de démonstration</p><div className="mt-4 grid gap-3 text-sm text-white/65 md:grid-cols-4">{["Cadrage", "Prototype", "Validation", "Déploiement"].map((step, index) => <span key={step}><b className="block text-[#f3d99d]">0{index + 1} · {step}</b>Étape structurante à suivre.</span>)}</div></section></>; }

export default function PublicRoute({ slug }) {
  const [title, lead, body] = copy[slug];
  const content = slug === "financer-mon-projet" ? <FundingForm /> : slug === "investir" ? <ProjectCards interactive /> : slug === "bawon-connect" ? <ConnectBoard /> : slug === "partenaires" ? <PartnerGrid /> : slug === "actualites" ? <UpdateFeed /> : slug === "accompagnement" ? <div className="grid gap-4 md:grid-cols-4">{["Diagnostic", "Structuration", "Préparation investisseurs", "Développement international"].map((item, index) => <div key={item} className="bawon-card"><span className="text-[#d6b26f]">0{index + 1}</span><h3 className="mt-8 font-semibold">{item}</h3><p className="mt-3 text-sm leading-6 text-white/60">Étape de démonstration avec livrables, tâches et suivi coordonné.</p></div>)}</div> : slug === "soutenir" ? <ProjectCards /> : ["bawon-produits", "bawon-boissons", "bawon-industrie"].includes(slug) ? <EcosystemPole slug={slug} /> : <div className="bawon-card text-white/70">Le futur espace public affichera les conditions, documents et règles de conformité avant toute action.</div>;
  return <Layout><main className="py-12 md:py-16"><DemoBanner /><p className="bawon-eyebrow">BAWON+ · {lead}</p><h1 className="mt-3 max-w-3xl text-4xl font-bold sm:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{body}</p><section className="mt-10">{content}</section><Link href="/" className="mt-10 inline-block text-sm text-white/70 hover:text-[#d6b26f]">← Retour à l'accueil</Link></main></Layout>;
}

export function getStaticPaths() { return { paths: Object.keys(copy).map((slug) => ({ params: { slug } })), fallback: false }; }
export function getStaticProps({ params }) { return { props: { slug: params.slug } }; }
